version: "3.7"

services:
  app:
    image: testing
    ports:
      - 3000:8080
    depends_on: 
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: webapp

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp

volumes:
  mysql-data: